version: '3.5'

services:
  client:
    container_name: react-dash
    env_file: .env
    environment:
      - REACT_APP_ENV=${REACT_APP_ENV}
      - REACT_APP_DOMAIN_PROD=${REACT_APP_DOMAIN_PROD}
      - REACT_APP_DOMAIN_STAG=${REACT_APP_DOMAIN_STAG}
      - REACT_APP_DOMAIN_DEV=${REACT_APP_DOMAIN_DEV}
    restart: always
    build:
      context: ./react-dash
      dockerfile: Dockerfile
      args:
        - REACT_APP_ENV=${REACT_APP_ENV}
        - REACT_APP_DOMAIN_PROD=${REACT_APP_DOMAIN_PROD}
        - REACT_APP_DOMAIN_STAG=${REACT_APP_DOMAIN_STAG}
        - REACT_APP_DOMAIN_DEV=${REACT_APP_DOMAIN_DEV}
    depends_on:
      - api
    ports:
      - 80:80

  api:
    container_name: elsaserver
    env_file: .env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
    restart: always
    build:
      context: ./elsaserver
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

  db:
    container_name: elsametric
    env_file: .env
    environment:
      - DB_POSTGRESQL_PORT=${DB_POSTGRESQL_PORT}
      - DB_RESTORE=${DB_RESTORE}
      - DB_DIALECT=${DB_DIALECT}
      - POSTGRES_DB=${DB_POSTGRESQL_SCHEMA}
      - POSTGRES_USER=${DB_POSTGRESQL_USER}
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - ${DB_POSTGRESQL_PORT}:${DB_POSTGRESQL_PORT}
    volumes:
      - ~/Downloads/${DB_POSTGRESQL_CONTAINER_NAME}:/var/lib/postgresql
      - ~/Downloads/${DB_POSTGRESQL_CONTAINER_NAME}/data:/var/lib/postgresql/data
