version: '3.5'

services:
  api:
    container_name: elsaserver
    env_file: .env
    environment:
      - SERVER_PORT=${SERVER_PORT}
    restart: always
    build:
      context: ./elsaserver
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

  db:
    container_name: elsametric
    env_file: .env
    environment:
      - DB_POSTGRESQL_PORT=${DB_POSTGRESQL_PORT}
      - DB_RESTORE=${DB_RESTORE}
      - DB_DIALECT=${DB_DIALECT}
      - POSTGRES_DB=${DB_POSTGRESQL_SCHEMA}
      - POSTGRES_USER=${DB_POSTGRESQL_USER}
    restart: always
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - ${DB_POSTGRESQL_PORT}:${DB_POSTGRESQL_PORT}
    volumes:
      - ~/Downloads/${DB_POSTGRESQL_CONTAINER_NAME}:/var/lib/postgresql
      - ~/Downloads/${DB_POSTGRESQL_CONTAINER_NAME}/data:/var/lib/postgresql/data
